### PR TITLE
修 bs markup問題

### LINKED ISSUE #313: bs本底 id 125無才調khiām

### PR DESCRIPTION
**Pull request by sih4sing5hong5**
fix #313

### CODE REVIEW

**Comment by niauah** [comment]
```
ERROR: test_分號 (tests.SuiSiannAdminApp.commands.test匯出Dataset試驗.匯出Dataset試驗)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/khing-iong/git/SuiSiann-KauTui/tests/SuiSiannAdminApp/commands/test匯出Dataset試驗.py", line 53, in test_分號
    call_command('匯出Dataset', kiatko)
  File "/home/khing-iong/git/SuiSiann-KauTui/.tox/test/lib/python3.6/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/khing-iong/git/SuiSiann-KauTui/.tox/test/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/khing-iong/git/SuiSiann-KauTui/SuiSiannAdminApp/management/commands/匯出Dataset.py", line 54, in handle
    原始音檔 = 句.音檔檔案
  File "/home/khing-iong/git/SuiSiann-KauTui/SuiSiannAdminApp/models.py", line 94, in 音檔檔案
    return join(settings.MEDIA_ROOT, self.音檔所在)
  File "/home/khing-iong/git/SuiSiann-KauTui/SuiSiannAdminApp/models.py", line 87, in 音檔所在
    return self.音檔所在表[self.音檔]
KeyError: <FieldFile: Oct 13, 2018 _243.wav>
```
音檔所在表格式：
```py
{'Oct_13_2018__243_A16kdAA.wav': 'tests/SuiSiannAdminApp/commands/Oct_13_2018__243_A16kdAA.wav', 
'Oct_13_2018__243.wav': 'tests/SuiSiannAdminApp/commands/Oct_13_2018__243.wav', 
'Oct_13_2018__243_swOSqih.wav': 'tests/SuiSiannAdminApp/commands/Oct_13_2018__243_swOSqih.wav'}

**Comment by sih4sing5hong5** [comment]
> ```
> ERROR: test_分號 (tests.SuiSiannAdminApp.commands.test匯出Dataset試驗.匯出Dataset試驗)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/khing-iong/git/SuiSiann-KauTui/tests/SuiSiannAdminApp/commands/test匯出Dataset試驗.py", line 53, in test_分號
>     call_command('匯出Dataset', kiatko)
>   File "/home/khing-iong/git/SuiSiann-KauTui/.tox/test/lib/python3.6/site-packages/django/core/management/__init__.py", line 181, in call_command
>     return command.execute(*args, **defaults)
>   File "/home/khing-iong/git/SuiSiann-KauTui/.tox/test/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
>     output = self.handle(*args, **options)
>   File "/home/khing-iong/git/SuiSiann-KauTui/SuiSiannAdminApp/management/commands/匯出Dataset.py", line 54, in handle
>     原始音檔 = 句.音檔檔案
>   File "/home/khing-iong/git/SuiSiann-KauTui/SuiSiannAdminApp/models.py", line 94, in 音檔檔案
>     return join(settings.MEDIA_ROOT, self.音檔所在)
>   File "/home/khing-iong/git/SuiSiann-KauTui/SuiSiannAdminApp/models.py", line 87, in 音檔所在
>     return self.音檔所在表[self.音檔]
> KeyError: <FieldFile: Oct 13, 2018 _243.wav>
> ```
> 
> 音檔所在表格式：
> 
> ```python
> {'Oct_13_2018__243_A16kdAA.wav': 'tests/SuiSiannAdminApp/commands/Oct_13_2018__243_A16kdAA.wav', 
> 'Oct_13_2018__243.wav': 'tests/SuiSiannAdminApp/commands/Oct_13_2018__243.wav', 
> 'Oct_13_2018__243_swOSqih.wav': 'tests/SuiSiannAdminApp/commands/Oct_13_2018__243_swOSqih.wav'}
> ```

這是你電腦走--ê？照`.travis.yaml`內底有音檔

**Comment by niauah** [comment]
https://stackoverflow.com/questions/67822500/django-nonetype-object-is-not-callable

**Comment by niauah** [comment]
> 照.travis.yaml內底有音檔
有解決--ah

**Review by niauah — APPROVED** [review]

**Review by niauah — APPROVED** [review]

**Pull request merged**
